### ISSUE TITLE
Make NSFW toggle dynamic

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#11]
**Is your feature request related to a problem? Please describe.**
Currently, checking/unchecking NSFW doesn't take effect until refresh/page load/etc. I usually browse with it unchecked, but sometimes emergency eye bleach is needed. On the flip side, sometimes browsing with NSFW on blurs out images that clearly are not actually NSFW (though marked as such for some reason) and one might want to see them.

**Describe the solution you'd like**
The blur should be dynamically applied/removed to any images currently displayed when checking/unchecking.

**Comment by BlafKing** [comment]
Sounds like a good request to me!

I didn't create the original NSFW hiding code, which upon inspection hides any tiles which are marked as NSFW and it also blurs any images/tiles which are tagged with anything else other than "None".
There is a tag for images which is "Soft" which imo does not count as NSFW, these were the tiles you saw blurred out whilst the "real" NSFW tiles were fully hidden (these were probably also the tiles you saw being blurred that were clearly not NSFW).

I've changed the code so that any images that are **not** tagged with "None" or "Soft" now get blurred.
This will cause no Tiles to be blurry anymore in the model selection since NSFW tiles are hidden and Soft tiles are no longer blurred.
Images from the model info after you select a model can still get blurred out though if they are not tagged with "None" or "Soft"

It also updates the blurring/hiding dynamically now using javascript!

These changes are applied in 1.7.2! 👍🏻
