### ISSUE TITLE
[BUG] After download failure, the download button stays disabled until refreshed.

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#12]
**Describe the bug**
After model fails to download and "Please try again" message appears, the download button stays disabled.

**To Reproduce**
1. Click on Download button.
2. After retrying then failing to download, "Please try again" message appears.
3. Download button stays disabled.

**Expected behavior**
Download button should re-enable. As a workaround, selecting the model thumbnail again refreshes the data and re-enables the download button.

**Comment by BlafKing** [comment]
Good catch!
I see now that this issue also occurred when a download is completed without failing and when the Cancel button was pressed since the download_finish and download_cancel functionss return the download button is non interactive.

I've added a check which sees if there is a filename inside the Model Filename box and if so, the download button it set to interactive upon returning from either functions.

This issue is now fixed in 1.7.2! 👍🏻
