### ISSUE TITLE
[Feature Request] Option to update tags for already downloaded Models

### ISSUE THREAD

**Issue by couldnt-find-good-name** [BlafKing/sd-civitai-browser-plus#15]
**Is your feature request related to a problem? Please describe.**
Option to update/create tags for already downloaded Models

**Describe the solution you'd like**
I have downloaded few Loras through your extension with save tags after download enabled. Tags/activation text are huge help while genearting in sd webui

**Describe alternatives you've considered**
Currently i have 1000+ loras downloaded, and its impossible to redownload all through the extension(not impossible though, but its time and bandwidth consuming.)

**Comment by ManOrMonster** [comment]
I was going to put in a similar request soon about generation data.

I still use the [Civitai Helper](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper) extension solely for its ability to scan all local checkpoints/LORAs/etc, then download preview images, generation data, activation tags, etc. It somehow manages to do this very quickly, also.

I mainly use this because it associates the prompt used to generate one of the preview images with the model. It adds custom buttons to the thumbnails in the extra networks to add these things to the prompt when clicked. The dev stopped updating it before auto1111 updated to 1.5 and added the new functionality, so it doesn't edit the json files.

The function is called "Scan Models for Civitai". You may want to check out how how that extension does it.

**Comment by BlafKing** [comment]
I've looked into the code of CivitAI Helper and they seem to use the Hash of the files for requesting model information.
I see now that the API supports requesting file info by supplying the hash of the file.
Using this method it should be possible to update all installed models with the matching tags.
It'll take a while since it still needs to do a seperate request per file but it should be possible this way, I'll start working on this feature!

**Comment by BlafKing** [comment]
The requested feature has now been implemented in v1.10!

There is now a new tab called 'Update All Tags' where you can select which folders to update, the script will then create a .json file for each model that is succesfully found on CivitAI! :)

Thanks for the request! I'll close this thread now since it's been resolved 👍🏻
