### ISSUE TITLE
[Feature Request] Speed up downloads by using Aria2

### ISSUE THREAD

**Issue by vorstcavry** [BlafKing/sd-civitai-browser-plus#17]
I use stable diffusion with Google Colab.

a feature that I think should be changed is the download process.

please add a download with aria2 so that the download process runs faster, in the current version I almost wait about an hour to download a model, compared to others, the civiai browser you made has very good patches, I look forward to making the download process faster and optimized.

**Comment by BlafKing** [comment]
I've now implemented Aria2 into the download_file function to speed up downloading in v1.9.
I spent some extra time to make sure it all works well with Linux too so it took a bit longer since I've never worked with Linux before and had to set-up a virtual box for testing.

Downloading with Aria2 should all work well on both Windows an Linux, lmk if you experience any issues!

**Comment by vorstcavry** [comment]
Thank you, this update is very cool, even I am amazed at the download speed which was originally very long to be very fast.

actually I also hope you can add the civitai gallery feature, a feature that can see reference images and can see information about the contents of the image or what can be called png info.
