### ISSUE TITLE
[Bug]: Extension API Error

### ISSUE THREAD

**Issue by Abishai2007** [BlafKing/sd-civitai-browser-plus#183]
### Describe the bug.

The Civit-API has timed out, please try again.
The servers might be too busy or down if the issue persists.

### Steps to reproduce the problem.

1. Go to extension tab
2. Press anything
3. The Civit-API has timed out, please try again.
The servers might be too busy or down if the issue persists.

### Expected behavior

To load civitai

### System info

* Extension version:
* OS:
* SD-WebUI version:
* Python:
Current standard install.

### Console logs

```Shell
I’ll add later…
```

### Additional information

I deleted my API and the error persists.

**Comment by Abishai2007** [comment]
Console Log
CivitAI Browser+: Error: HTTPSConnectionPool(host='civitai.com', port=443): Max retries exceeded with url: /api/v1/models?limit=15&page=1&sort=Most%20Downloaded&period=AllTime&nsfw=false (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EDB822CA60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by BlafKing** [comment]
This is unfortunately not something I can fix from withing the extension, as far as I can tell.

The error message you provided indicates that there was a failure to establish a new connection due to a "getaddrinfo failed" error. This typically occurs when the system is unable to resolve the hostname to an IP address.

If you can provide some more info about your system as requested in the bug report System info, I might be able to help, but it looks like it's not caused by the extension directly.
