### ISSUE TITLE
[Bug]:dont download  models

### ISSUE THREAD

**Issue by Fagnerfriedhofer** [BlafKing/sd-civitai-browser-plus#184]
### Describe the bug.

dont download any model. but download info, images and page.html

### Steps to reproduce the problem.

1.choose a model 
2. download the model

### Expected behavior

download de model from civitai

### System info

* Extension version: [9e70db57]
* OS: Manjaro linux
* SD-WebUI version: 1.7.0
* Python: 3.11.6-1

### Console logs

```Shell
CivitAI Browser+: Failed to start download: HTTPConnectionPool(host='localhost', port=24000): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f64c4dce310>: Failed to establish a new connection: [Errno 111] Connection refused'))
CivitAI Browser+: Error occured during download of "hellomecha_V10Beta.safetensors"
CivitAI Browser+: Model info saved to "/run/media/fagner/Storage_01/AI/Novo/stable-diffusion-webui-master/stable-diffusion-webui/models/Stable-diffusion/hellomecha_V10Beta.json"
CivitAI Browser+: Downloaded image 1
CivitAI Browser+: Downloaded image 2
CivitAI Browser+: Downloaded image 3
CivitAI Browser+: Downloaded image 4
CivitAI Browser+: Downloaded image 5
CivitAI Browser+: Downloaded image 6
CivitAI Browser+: Downloaded image 7
CivitAI Browser+: Downloaded image 8
CivitAI Browser+: Downloaded image 9
CivitAI Browser+: Downloaded image 10
CivitAI Browser+: Failed to start download: HTTPConnectionPool(host='localhost', port=24000): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f64cbbeb190>: Failed to establish a new connection: [Errno 111] Connection refused'))
CivitAI Browser+: Error occured during download of "hellomecha_V10Beta.safetensors"
```

**Comment by BlafKing** [comment]
This issue is likely caused by it failing to make a connection with the Aria2 client for any reason, I personally can't recreate this issue on Linux, but since the `/jsonrpc` states that it cannot reach the Aria2 RPC server, means that Aria2 is either unreachable or not running.

The solution in the [Known Issues tab](https://github.com/BlafKing/sd-civitai-browser-plus?tab=readme-ov-file#known-issues-) on the readme called `Revert to the old download method` should fix your issue.
