### ISSUE TITLE
[Bug]: Files being put in folder "Only available if the selected files are of the same model type"

### ISSUE THREAD

**Issue by beetanz** [BlafKing/sd-civitai-browser-plus#202]
### Describe the bug.

On line 90 you're adding setting default_subfolder = "Only available if the selected files are of the same model type"
This is causing files to be downloaded to a folder"Only available if the selected files are of the same model type" if no dynamic subfolders are selected.

### Steps to reproduce the problem.

1. Disable any dynamic folders ModelName/Version etc
2. batch download
3. ...

### Expected behavior

Folder created named "Only available if the selected files are of the same model type" with new models in it.

### System info

* Extension version: latest
* OS: Debian
* SD-WebUI version: 1.7.0
* Python: 3.10.13

### Console logs

```Shell
N/A
```

**Comment by beetanz** [comment]
Actually seems to be an issue if you regularly download something and then do a bulk download
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/15079926/2384250d-6bde-42fc-a156-b32d43c1e19a)

**Comment by beetanz** [comment]
Created #204 to resolve

**Comment by BlafKing** [comment]
Thanks for bringing this to my attention and for making a pull request!
However, I saw that you removed the entire "Only available if the selected files are of the same model type" message, which I'd like to avoid doing since this explains to the user when and why a sub folder cannot be used.

Instead I'll add some extra checks to make sure it's never used as an actual install path.

I'd also like to avoid adding too many insertable sub folders with just one settings, since not all users will need/want so many default sub folders, and this can make the sub folder dropdown quite cluttered.

Instead I'll add a little dropdown in the settings which can be used to select each individual insertable sub folder which the user would like to use:
![Screenshot 2024-02-17 134027](https://github.com/BlafKing/sd-civitai-browser-plus/assets/9644716/47ed6269-a6e0-4e9b-ba83-2b502af06b0e)

I appreciate you taking the time to make a pull request, but since I will change quite some things, I won't be merging it and I'll instead include all of the changes I mentioned in the upcoming update.

Thanks again for taking your time to dig into my spaghetti code and submit everything though, it is appreciated! :)

**Comment by BlafKing** [comment]
The mentioned changes are now included in the latest version! :)

I'll go and mark this as resolved

**Comment by beetanz** [comment]
Ahh that's awesome! Thanks! That was fast! I was already digging in it because I wanted that folder structure... then found that while doing it. I wanted to consolidate the subfolder stuff into file_manage to avoid the duplication that's currently between download and API but I decided to take the easy way to at least fix this since it was making a mess.

I love this tool, I think this is the best civit manager for AUTO. I might play with some features in my fork and I'll let you know if I actually get something useful.
