### ISSUE TITLE
[Feature Request] Optimize download speed. Download using the ARIA2 provided by Motrix or other

### ISSUE THREAD

**Issue by Fanshiux** [BlafKing/sd-civitai-browser-plus#22]
## Is your feature request related to a problem? Please describe.
When downloading with ARIA2, the speed is too slow.

## Describe the solution you'd like
Optimize download speed.

## Describe alternatives you've considered
Download using the ARIA2 provided by Motrix or other.

## Additional context
[ARIA2 RPC](https://aria2.github.io/manual/en/html/aria2c.html)

Using the ARIA2 RPC service seems faster and more convenient than binaries

## Motrix (ARIA2 RPC)

![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/48909759/e295235c-5e0f-4f96-aa0f-e25a410f4632)

## ARIA2 binary

![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/48909759/b0b66d65-400b-4a3d-ad80-d8bb0b4fc546)

**Comment by BlafKing** [comment]
Thank you for bringing this to my attention.
It's important to note that the core downloading logic of Aria2 remains the same whether you use it directly or through its RPC interface. Both methods essentially tap into the same Aria2 code to handle downloads so it shouldn't impact raw download speed.

The speed differences you're experiencing are likely due to different Aria2 configuration settings in Motrix. Settings like the number of connections per server, split size, and other advanced options can influence download speed.

I've had a look at the Motrix default config and they seem to be splitting each download into 64 pieces and then setting a max of 64 connections
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/9644716/9f2488d4-8e25-4bfe-9325-236e4d4f86ed)

Motrix has compiled a custom version of Aria2 to achieve this since Aria2 has a hard cap of 16 max connections per server.

I'll see if it's possible to implement the version of aria2 that Motrix uses and set the max connections to 64 to help users like yourself with download speeds!

**Comment by BlafKing** [comment]
It'll be difficult to implement this for Linux since it's not easy to ship Aria2 with this extension for Linux which will be required since setting the max connections per server to 64 is not possible by default.
I'll try to troubleshoot further tomorrow to see if it's possible to ship this extension with Aria2 for Linux.

**Comment by BlafKing** [comment]
For now I've changed the split and max connections to 16, I'll see tomorrow if it's possible to increase this further by shipping Motrix's Aria2 with Linux, but, it'll most likely be very tricky to implement properly so can't guarantee that it'll work.

**Comment by BlafKing** [comment]
It looks like I've succesfully managed to ship the modified Aria2 for Linux as well in v1.9.3!
I've tested this extension on a clean install of both Linux-Mint and AlmaLinux and they both worked well without the need to manually install Aria2.
update v1.9.3 now also has the same config as Morix so it should improve your download speeds!

I'll close this thread but please feel free to send another message here if you encounter any issues!

**Comment by Fanshiux** [comment]
Thanks for your work and hope it gets better.😜
