### ISSUE TITLE
[Bug]: totalPages key error

### ISSUE THREAD

**Issue by BlafKing** [BlafKing/sd-civitai-browser-plus#229]
Just a heads up:

CivitAI has updated their API, and the extension is currently broken.
I've started working on a fix, but it might take a while since the paging system has been completely changed, which this extension relied on pretty heavily.

**Comment by debaetsr** [comment]
#228 is the same bug

**Comment by BlafKing** [comment]
> #228 is the same bug

Not exactly, the bug report was initially for runpod issues, which were likely caused by something else.

**Comment by debaetsr** [comment]
The bug is that Civitai changed their API, and the key totalPages doesn't exist anymore.

**Comment by BlafKing** [comment]
> The bug is that Civitai changed their API, and the key totalPages doesn't exist anymore.

I am aware, already working on a fix as stated in the post👍🏻

**Comment by BlafKing** [comment]
Little update:
The current code (like most of this extension) is a complete spaghetti mess and it broke a lot more than I anticipated.

After trying to patch in fixes for a few hours, it's really not going too well.
It's probably possible to patch in enough fixes for the new API but after looking at the abomination that's in front me, I've now opted to re-write most of the API handling code as continuing with the current code would create an ever bigger mess than what's already present.

This will be quite a lot of work, so it's going to take a while.
Rest assured though, I've got plenty of free time ahead so I'll try my best to get the update out ASAP!

**Comment by Kiramut** [comment]
I created an account specifically to say you fully deserve your name ~~and your bio~~

Thank you for your time <3

**Comment by schoenid** [comment]
> The bug is that Civitai changed their API, and the key totalPages doesn't exist anymore.

Even the key currentPage on the updates check ...

**Comment by JustMaier** [comment]
We had to switch to a cursor based model do to the volume of models now. Sorry for the surprise. I'll see if we can at least get those keys put back, but I don't think that alone will fix things here.

**Comment by JustMaier** [comment]
Just took a look at the codebase, looks like it's very heavily oriented around pages 😬

**Comment by BlafKing** [comment]
No worries, that's okay! makes sense that switching to a cursor-based model was necessary
I should have an update ready somewhere today that will be compatible with the new cursor system!

Only change for this extension will be that it will no longer be possible to jump directly to a specific page. which is a consequence of moving away from traditional pagination to a more scalable cursor approach.

I appreciate your efforts in maintaining and improving the API :)

**Comment by Xipomus** [comment]
Workarrond: For those who still want to download via the plugin, you can do 2 edits then the plugin works. Not as it should but you can browser civitai for urls and paste those in the search of the plugin to download.

- Go to the SD folder\webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py and open it in notepad or a different editor, (i would suggest Notepad ++.)
- line 327 says model_card = f'<figure class="civmodelcard {nsfw} {installstatus}" base-model="{baseModel}" date="{date}" onclick="select_model(\'{model_string}\', event)">'
 changed is to model_card = f'<figure class="civmodelcard {nsfw} {installstatus}" base-model="{baseModel}" onclick="select_model(\'{model_string}\', event)">'
 (removed the date, because the list wasn't giving a response to date and throwing an error of date nog begin defined)

- line 481 says total_pages = f"{json_data['metadata']['totalPages']}", changed that to total_pages = 1 
                                           (can be more off course, but you could get empty pages)

You can just search for the text and replace it off course. Might want to make a backup of the civitai_api.py before editing

This way the plugin works for now, just 1 page of results for now

**Comment by BlafKing** [comment]
I've now published an update which fixes the paging issues with the new API! [v3.5.0](https://github.com/BlafKing/sd-civitai-browser-plus/commit/6877d1b60a2b1e4bc69615adab833517f2a016ad)

Do note, it's no longer possible to jump directly to a specific page unless that page has already been visited, this is the result of the new "cursor" based paging system which was required due to the amount of models on CivitAI.

Also another note, currently the API returns the error:
```
Error: 500 Server Error: Internal Server Error for url
```
Quite often, there is nothing I can do about this, as this is an issue caused by the CivitAI API.
I assume this will get fixed after some time! :)
For the time being, I've made a bug report for it here: #233

Other than that, everything should be working again!
Please feel free to create a bug report if you encounter any other issues.

**Comment by schoenid** [comment]
Works great again.
Thank you so much!

**Comment by thebeline** [comment]
Looks like they have stopped hashing new models.  Can anyone confirm?

**Comment by BlafKing** [comment]
> Looks like they have stopped hashing new models. Can anyone confirm?

Looks like this has now been fixed 👍🏻

**Comment by schoenid** [comment]
@thebeline 

> Looks like they have stopped hashing new models. Can anyone confirm?

As I can see on:
[Lunarity XL Turbo](https://civitai.com/models/355082/lunarity-xl-turbo)
This brand new model has a hash.
