### ISSUE TITLE
[BUG] Tab vanished after update 

### ISSUE THREAD

**Issue by Darkpo8** [BlafKing/sd-civitai-browser-plus#27]
**Describe the bug**
Tab not showing after update

**To Reproduce**
1. Update through Extension tab
2. Apply and restart UI

**Expected behavior**
To see the tab? i guess.. :)

**Screenshots**
<img width="1197" alt="Screenshot 2023-09-14 at 12 42 57" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/62176401/0a85bd78-b09f-4eb3-bbde-7a8dcc0e5673">

**Additional context**
* Extension version: latest
* OS: Mac OS, latest
* SD version: A111 latest
* Python: latest
* Any Additional info
Thanks!

**Comment by BlafKing** [comment]
Thanks for notifying me about the issue!
Currently this extension does not support MacOS since the Aria2 package for MacOS is not shipped with the extension.
I'll install MacOS on a VirtualBox to attempt to include Aria2 for MacOS, otherwise I'll adjust the extension so that it'll work on MacOS without Aria2. 👍🏻

**Comment by BlafKing** [comment]
There's a previous bug thread about the same issue right now so I'll close this one and continue the issue over here:
https://github.com/BlafKing/sd-civitai-browser-plus/issues/26
