### ISSUE TITLE
[Bug]: Downloading all html despite unchecked

### ISSUE THREAD

**Issue by silveroxides** [BlafKing/sd-civitai-browser-plus#293]
### Describe the bug.

The extension updates html of each model while "Overwrite any existing files. (previews, HTMLs, tags, descriptions)" is checked even if "Save HTML file for each model when updating info & tags (increases process time)." is unchecked. If the mentioned issue is working as intended then the should be "increses process time" warning there too or at least and indicator that it enabled all html download. 

![sEZxnAU2iK](https://github.com/BlafKing/sd-civitai-browser-plus/assets/65376327/ebad4533-1456-4687-994a-251abd3eb547)

Can't say I was happy to see 1631 files being processed and since the extension chooses to display each file gone through as a progress update in gradio the entire browser is having staggering issues. It peaked at around 420 at which the tab crashed.
You can see by my system specs that it is not a slow PC. Maybe consider if your code might need some optimization

![msedge_5Af0gCqpag](https://github.com/BlafKing/sd-civitai-browser-plus/assets/65376327/a661e193-f5cb-45fd-97a0-d659bbb7fc44)

### Steps to reproduce the problem.

Go to Update Models. Repeat the actions I described.

### Expected behavior

Not to Download 1631 html unless "Save HTML file for each model when updating info & tags (increases process time)." is checked while  "Overwrite any existing files. (previews, HTMLs, tags, descriptions)" is checked. 

### System info

* Extension version:Same as last issue
* OS:Win11 pro
* SD-WebUI version:1.8.0
* Python:3.10.9
* 13th Gen Intel(R) Core(TM) i5-13600K overclocked to 5.2 GHz
* 64 GB RAM
* RTX 4060 ti 16GB

### Console logs

```Shell
Only thing there is:

CivitAI Browser+: HTML saved at "C:\Stable_Diffusion\stable-diffusion-webui\models\Lora\subdir\LoRAname.html"
CivitAI Browser+: Model info saved to "C:\Stable_Diffusion\stable-diffusion-webui\models\Lora\subdir\LoRAname.json"
```

**Comment by BlafKing** [comment]
Thanks for pointing out the issue, after a quick skim it looks like the issue is caused by a little oversight, there is a condition where it states

```py
if create_html and not os.path.exists(html_path) or overwrite_toggle
```
So it looks like it currently generates a new HTML file when the overwrite toggle is on regardless of other options.
Will include a fix for this in the next update when I finally have some time to write new changes :,) 👍🏻 

About your comment stating that the code is unoptimized, it most definitely is and that's not gonna change anytime soon.
I'm not by any means experienced when it comes to python code nor the inner working of the Gradio UI library.
This is, after all, a solo project I made in my free time with little to no experience. (And not a paid program where you can expect quality)

**Comment by BlafKing** [comment]
Made a small hotfix to the line which should hopefully resolve your issues, can't test the code right now as I won't be home for a while/won't be able to run SD-Webui for a while, so let me know it has fixed the issue 👍🏻

**Comment by silveroxides** [comment]
Working as intended now. 186 models took ~6 seconds post API call to update info and tags for which is a huge improvement.
