### ISSUE TITLE
[Feature Request] Show Current Models

### ISSUE THREAD

**Issue by Worldgate** [BlafKing/sd-civitai-browser-plus#32]
Would it be possible to show the current models installed so that you can search for them based on what ever hash they have.  Currently you can use the V2 hash to search using your addon, it would be very convient to show the list of current files and search for the data for them.  I only ask this because i've downloaded a lot of lora's from various sources that i have no idea what they do (yes im a bit of a horder) and been hashing and searching via this addon to find out their info then packaging them into zips.  If the model is ever deleted, which happens a lot, i have the html info and images in my zip.

Also thanks for adding that feature to goto a directory. :)

**Comment by BlafKing** [comment]
Thanks for the request!
To clarify, you'd like an option that loads all installed models from the selected category into the browser so that they get assigned a sha256 hash and so that you can view info about them?
Sounds like a good feature to me!

Also no worries about adding the sub folder feature! glad you find it useful :)

**Comment by BlafKing** [comment]
v1.12 now has the ability load all installed models into the browser in the Update Models tab.

Took a bit longer to implement since I had to partially rewrite a lot of functions to work with multiple content types.
the install status scanning is now also improved by also using the SHA256 to find installed files.

I'll close this thread now since the feature you requested is now implemented! :)
