### ISSUE TITLE
[help] please advise how " Save tags after download " work?..

### ISSUE THREAD

**Issue by seset** [BlafKing/sd-civitai-browser-plus#34]
I am quite a beginner for using models...
do these saved tags mean Trained Tags, which can enchance prompt like lora or embeddings do?
Is there an easy ways to load Trained Tags(if any) to prompt? or display hints for trained tags somewhere as reference when using a certain model?
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/33795620/61c02739-2a35-46e1-ab11-6ec6fba69f96)

**Comment by BlafKing** [comment]
The trained tags are indeed tags that can help enhance the prompt for LORA's and Embeddings and things alike.
They are tags that the original uploader has provided for users to use to help with creating images.

If you use a version of [A1111 Stable Diffusion](https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases) later than 1.5 then these tags will automatically be used when you select any model of which the tags are saved! :)
There is also an option to save tags for all already installed models! :)

I'll close this thread since it's not an issue but feel free to ask any other questions if you have them!
