### ISSUE TITLE
[Bug]: Tags are not shown in correct order

### ISSUE THREAD

**Issue by Lumerica** [BlafKing/sd-civitai-browser-plus#357]
### Describe the bug.

I create subfolders based on the first found tag in CivitAI added part of that in the code. Since I use the first found CivitAI tag to create the sub folders the existing bug actually made me realize that there is a bug in the way how the tags are fetched. https://github.com/Lumerica/sd-civitai-browser-plus_fix/commit/3a2fc484620659d3d3f02ecaa24b15994280b15a#diff-3596f008aa2de94abe1787cc6646834d48a4ca75b47908742a027eedc4f66086R1049

This issue happens with latest version ([807a21c3](https://github.com/BlafKing/sd-civitai-browser-plus/commit/807a21c318a03a4e3bab8b84c6246e8e50331307)) but also in previous version ([0b97a482](https://github.com/BlafKing/sd-civitai-browser-plus/commit/0b97a482ad4e3c0fec797a797414a0f0eeef08fa))I am using.

### Steps to reproduce the problem.

Search for any model, check the model in SD, compare the CiviAI tags with the website, and you wills see there that the order is different.

![image](https://github.com/user-attachments/assets/abeaf3aa-59f5-457f-a9ad-6b41b62e56f8)

### Expected behavior

The order of the tags should be exactly same as how it is represented by the author. Even though first tag does not always makes sense set by the author. At least it should respect the first tag.

Console log + whats happening:
![image](https://github.com/user-attachments/assets/7e1c580e-3fe4-4bfa-b22d-343605db20d3)

### System info

* Extension version: any version
* OS: Win 10
* SD-WebUI version: Automatic1111 & Forge UI
* Python: 3.10.10

### Console logs

```Shell
CivitAI Browser+: Found 1 model(s) on current page.
CivitAI Browser+: The selected model has 1 version(s).
CivitAI Browser+: Selected model: "AsunaTitania (SAO) 亚丝娜蒂塔妮亚" Version: "v1.0"
CivitAI Browser+: civitAI automatic tagging for this model is: "anime"
CivitAI Browser+: The author assigned the following 5 civitAI tag(s) for this model: "anime, character, sao, sword art online, asuna".
CivitAI Browser+: First civitAI tag "anime" will be used for sub-folder creation if configured in settings.
===============================================================================
```

### Additional information

This is a modified version where I retrieve the found models on current page (was not able to actually get the actual numbers of models found if it exceeds current page before paging) and also get the model version selected and retrieve the number of versions the selected model has (because I was not able to find a way to indicate how many versions a model has on the UI.
Anyway, ignore all these,  the focus is the tag message you can see what is happening in the console. The website shows that the first tag is actually "character", which is the correct first tag.

**Comment by BlafKing** [comment]
Thanks for reporting!

I think the issue mainly resides in the public REST CivitAI API, not this code, as this code simply grabs the order that the CivitAI API returns.
The results between the site and this extension differ because the site uses an internal private API, rather than the public API.
You can see this behavior yourself when you use the public API using: `https://civitai.com/api/v1/models/87851`
The tags section returns:
```
"tags": [
    "anime",
    "character",
    "sao",
    "sword art online",
    "asuna"
]
```
So it looks like this issue resides more on CivitAI's end rather than this extension.
If you'd like you can report it on their github [here](https://github.com/civitai/civitai/issues/new?assignees=&labels=bug-report&projects=&template=bug_report.yml&title=%5BBug%5D%3A+)

I'll close this issue as there's no real discernible way to detect which tag is the "main" tag.
