### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cgwers** [BlafKing/sd-civitai-browser-plus#36]
**Describe the bug**
Ineffective model filtering

**To Reproduce**
1.  Filter Base Model: SD 2.0
2. Content Type: LORA

**Expected behavior**
I expect to see ONLY LORA for SD 2.0.  

Likewise, with any criteria selected, the filter should only return matching content, not display _all_ content using enabled/disabled cards. Displaying the disabled cards provides nothing of value to users. 

Why is this bad? When the result displays several valid cards sprinkled amongst the disabled cards and page counter says 1/1043, when does the user stop paging looking for a valid results? If there are hits on the second and third pages, do you expect the user to go through _all_ the pages looking for more?

**Screenshots**

**Additional context**
* Extension version: [768b8dee](https://github.com/BlafKing/sd-civitai-browser-plus/commit/768b8deebae59b42dcb36e19fb70c92b226f0cb2)
* OS: OS (Windows 10 )
* SD version: SDWEB
* Python: Python version in SD-WebUI
* Any Additional info

**Comment by BlafKing** [comment]
Unfortunately this is currently not possible since the API does not support filtering search results based on Base Model.
The filter is currently implemented as a work around but is indeed far from perfect.

there's currently no alternative until the API gets updated and properly supports filtering search results on Base Model.

You can upvote my feature request [here](https://civitai.featurebase.app/submissions/64ea19ac4f9cf39e6f9fb2e9) and [here](https://github.com/orgs/civitai/discussions/733) to hopefully have this feature implemented soon!

I already have planned to implement proper Base Model searching as soon as the API gets updated with this feature.

**Comment by BlafKing** [comment]
I'd just like to add that it turns out that the API does support this after all, but it's not documented on the docs like some other features they added later on 🙃
I'll post an update today so that Base Model filtering actually impact search results! :)
