### ISSUE TITLE
[BUG] Recent style changes break many other tabs

### ISSUE THREAD

**Issue by GeBo1** [BlafKing/sd-civitai-browser-plus#37]
**Describe the bug**
Recent style changes break many other tabs. Entries in style sheet should probably be scoped  (prefix with `#tab_civitai_interface`)

Reverting to v1.11 fixed the issue.

**To Reproduce**
1. Activate img2img tab
2. Click on inpaint
3. press `S` key on keyboard to go to fullscreen editor
4. canvas does not expand properly

Or if you have openOutpaint installed:
1. Activate openOutpaint tab
2. see that it only displays the top few pixels of the editor

**Expected behavior**
This extensions styles only apply to this extension.

**Additional context**
* Extension version: v1.11.2 or greater
* OS: Windows
* SD version: v1.6.0
* Python: 3.10.6

**Comment by BlafKing** [comment]
Thanks for letting me know!
I've published a hotfix that now uses the prefix for the preview element `civitai_preview_html`
when addressing the relevant style changes.

@ManOrMonster Could you let me know if you find any issues with the way that the style.css currently applies to the model page?

I've removed `vertical-align: middle;` from `.avatar img` since it's ignored due to the `display: block;`
I've also removed the `margin-bottom: -10px;` from `.model-block h2` since the margin seems to be smaller by default when addressing `civitai_preview_html` directly (might be wrong about that though but looks good afaict)

Feel free to send me a msg here if you find something that's wrong or just make a pull request with a fix, anything is fine! :)

**Comment by ManOrMonster** [comment]
Looks good, sorry for breaking other tabs!

**Comment by ManOrMonster** [comment]
@BlafKing Hey, can you make this quick change to the image width line in scripts/civitai_api.py? I think this is the best way to handle preview image size. It auto sets every image to have a width equal to its original size.

Change this:
```
# Change small width value (usually auto set to 450) in img URL to "full"
image_url = re.sub(r'/width=\d+', '/width=full', pic["url"])
```

to this:
```
# Change width value in URL to original image width
image_url = re.sub(r'/width=\d+', f'/width={pic["width"]}', pic["url"])
```

**Comment by BlafKing** [comment]
Sounds good! I'll publish a quick change for this👍🏻
