### ISSUE TITLE
Feature Request: Browse while downloading

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#4]
This extension has helped a lot so far with my morning ritual of browsing through all the new LORAs/LoCons. However, having to wait for each download instead of continuing to browse slows down the process quite a bit.

**Issue**: Having to wait for a download to complete to continue browsing.

**Solution**:  The download button adds the download task to a queue. Download progress is displayed in the queue itself next to each download instead of overlaying the browser. If any download tasks fail, a retry button will appear next to them in the queue.

**Comment by BlafKing** [comment]
I'd like for this to be added as well, but it would require a complete rewrite of the current way that download progression is shown to the user, furthermore, it will be difficult to implement this since the gradio UI only updates upon a function returning.

I'd have to find a way that each download creates a new gradio component, which then need to trigger and return the corresponding download thread, since the download progression bar can only be shown in gradio if the function is waiting to be returned, which would require a seperate component for each download.

I'll see if I can implement this but don't count on it since I more than likely don't have the required python skill to implement this properly.
I've only started learning python about 3 months ago :,)

**Comment by ManOrMonster** [comment]
Would it be possible to make the download status appear separately instead of covering thumbnails, and still allow browsing?

**Comment by BlafKing** [comment]
> Would it be possible to make the download status appear separately instead of covering thumbnails, and still allow browsing?

That could definitely be possible!
I'll see if I can insert a new HTML component to allow a separate download progression so that you can keep browsing 👍🏻
I'll open this thread again until I've implemented that since that seems much more reasonable :)

**Comment by BlafKing** [comment]
I've just gone an updated the script to include being able to browse whilst a model is being downloaded!
I'll go and close this thread now since the requested changes are now implemented! :)

**Comment by ManOrMonster** [comment]
This is going to speed up my daily downloads considerably. Thank you!
