### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by illuculent** [BlafKing/sd-civitai-browser-plus#56]
'Save settings as default" window won't go away. I go into the page and it is there on top of everything and won't go away, no matter what I click on. Work just fine until I updated it.

**Comment by BlafKing** [comment]
There's unfortunately not enough info here for me to find out what could cause this issue.
Please provide more info such as:

OS:
SD version:
Python version:

A screenshot of the issue would also help.

**Comment by BlafKing** [comment]
A small issue is that that window is currently not hidden by default and requires the user to press the button twice to hide it.
I'll make sure to publish a quick fix for this along with the other bug fixes which I hope to publish today.

**Comment by silveroxides** [comment]
[Link to image of error message appear](https://i.imgur.com/kEHSZ5L.png)
Yes the errors appears after closing dropdown. Extremely unintuitive either way.
Also saving defaults is not possible because the button simply does not work at all since the tab does the processing as soon as it is opened and errors out before one even would have the chance to set a default. Maybe there should be a default default ;)
This is one of the error codes I am presented with. 

`Traceback (most recent call last):
  File "V:\Users\ishim\stable-diffusion-webui\webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "V:\Users\ishim\stable-diffusion-webui\webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "V:\Users\ishim\stable-diffusion-webui\webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "V:\Users\ishim\stable-diffusion-webui\webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "V:\Users\ishim\stable-diffusion-webui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "V:\Users\ishim\stable-diffusion-webui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "V:\Users\ishim\stable-diffusion-webui\webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "V:\Users\ishim\stable-diffusion-webui\webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 415, in update_model_list
    HTML = model_list_html(gl.json_data, model_dict)
  File "V:\Users\ishim\stable-diffusion-webui\webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 241, in model_list_html
    json_data = json.load(f)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 971: character maps to <undefined>
`

**Comment by BlafKing** [comment]
The filter dropdown isn't just for setting defaults, it's for applying the filter settings you'd like to use when searching CivitAI.
IMO not unintuitive at all, the previous layout was a mess and this cleans things up.

The `save settings as default` button is for saving the settings you have applied as default, which is just a simple add-on.
The full filter box isn't made to just save defaults, it's made to select the specific filter settings you'd like to use when browsing CivitAI.

The error you are receiving also has nothing to do with the Filter box, it's related to an error in decoding the .json return of the API request, it's present as soon as you open the extension because the extension attempts to load a default page with the default settings.

Please provide the info I requested in the previous post and I'll happily look into why you're receiving this error:

Extension version:
OS:
SD version:
Python version:

**Comment by silveroxides** [comment]
Sorry about that. Been so frustrating since 1.6.0 released and it has been an avalanche of stuff breaking one after the other ever since.

Edition	Windows 11 Pro
Version	22H2
Installed on	‎2022-‎10-‎27
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0
version: [v1.6.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4)  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  •  checkpoint: [519aeb1f64](https://google.com/search?q=519aeb1f64842c0fbf31a6e29b7409fe11383eb9395a0a4ef8125698ef6a5f0c)

**Comment by BlafKing** [comment]
Thanks for the description, the error is a simple decoding error where it attempts to read a (presumably) broken .json file.
(Which I didn't properly catch the error for)
I've published a quick hotfix for it, please let me know if it has solved your issue :)

**Comment by Manniala** [comment]
Well works fine for me right now, popup is closed when i to to Civit AI (your extension), and played around with it for a bit, and did not get any error messages.

And thx for the ENTER press and search, no more press buttons 👍

**Comment by illuculent** [comment]
OS: Windows 11
SD version: 1.6.0
Python version: Python 3.10.11

I believe this is the latest version of everything. All extensions updated.
Installed using Stabilty Matrix which lets me know of any updates avialable.
Before using every time:
I update SD first, if available.
I update all extensions.
I then apply all setting as extension update may have modified or created parameters.

**Comment by BlafKing** [comment]
Thanks for the extra info.
It's likely that your error has been fixed, since the latest version should work fine with Windows 11.
(I've updated my reply here on github, but that hasn't updated in your email)
You can toggle the Filter window by pressing the filter button above it.

Please let me know if this works for you, if so I will close this bug thread.

**Comment by BlafKing** [comment]
> [EDIT] There is 1 thing i would like, when you press "Save settings as default" that the popup than closes, in my head (yep got one, not used much but got it :)), you are done there once you press save. :)

Unfortunately Gradio doesn't seem to allow directly updating the Accordion/pop up window from outside the button.
I've also tried closing the window with javascript but that also doesn't work well, unfortunately it seems like the only way to properly close it by using the button itself :/

**Comment by silveroxides** [comment]
Sadly I cannot check if anything worked. Out of nowhere my entire installation just went and gave up.
For some reason bitsandbytes started looking in Linux directories and stuff. 
So tired of all of it. If I get it up and running again I will report if stuff worked

**Comment by illuculent** [comment]
That is frustating... this trying to plant a flag on constantly moving ground. I comisurate. Some good new though. The window is no longer there when I go into that page. Yeah!!! ... but short lived. All I see now is 6 twirling orange boxes. Whatever they are trying to receive, does not seem to be working. Reminds of the old coding joke: There are 100 bugs left to fix. Fixed one of them. Now there are 106 bugs left to fix.

**Comment by illuculent** [comment]
It is true that the 'Save settings as default" window is no longer there when I go into that page but when I click on filters and it pops up, the 'Save settings as default" window won't go away. In the background I have the 'loading' twirling orange boxes. they are doing that constantly from the moment I select that page to anything clicked within it. They may be preventing the 'close window' code from running. Maybe that will help to locate the source of this issue.

**Comment by BlafKing** [comment]
That unfortunately does not help, loading boxes can mean anything and I need a clear indication as to what is going wrong.
It shouldn't be possible for them to keep loading for ever, since there is an API timeout of 30 seconds, after 30 seconds, they should either time out or print out an error in the CMD.

Could you see if an error gets printed? If not there isn't much I can do.
If there isn't an error, it could also maybe help if you post your full CMD logs.

Again, I need something that points me to the error, since a loading box can mean anything.

**Comment by ManOrMonster** [comment]
I just wanted to add here that the "Save settings as default" button does not save any defaults for me either. There's no feedback, no error message in console, just seems to do nothing. Until the recent update, it was still loading the settings I had set through "Defaults" in auto1111 Settings, but no more. Also, the button looks different for me (maybe since I don't use a theme extension):

<img width="282" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/b18828a5-ffd6-43d3-aea8-a3adba2c055b">

**Comment by BlafKing** [comment]
> I just wanted to add here that the "Save settings as default" button does not save any defaults for me either.

It should save the defaults to ui-config.json, Have you tried restarting SD-WebUI after pressing save settings as default?
The button should properly write the changes to ui-config.json if no errors appear.

>  Until the recent update, it was still loading the settings I had set through "Defaults" in auto1111 Settings

My OCD had to fix the capitalization of the filter descriptions :,) (Search Type > Search type) for example which has probably caused your default settings to be reset since the default settings are set by name, and are case sensitive.

Please let me know if the save button does work for you after restarting or if it doesn't work at all :)
I'll also make sure to fix the padding on the button, didn't test it without a theme so that's my bad 😅

**Comment by ManOrMonster** [comment]
Restarting didn't do anything. Config.json settings:

```
    "civitai_link_key": null,
    "civitai_link_logging": true,
    "civitai_api_key": "",
    "civitai_download_previews": true,
    "civitai_nsfw_previews": false,
    "civitai_download_missing_models": true,
    "civitai_hashify_resources": true,
    "civitai_folder_model": "",
    "civitai_folder_lora": "",
    "civitai_folder_lyco": "models/lora",
```

**Comment by ManOrMonster** [comment]
I saw this in ui-config.json

<img width="250" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/177c1e85-2b04-41f7-a2cf-597101e6060a">

**Comment by BlafKing** [comment]
Think I found the issue, small note though, the correct file is ui_config.json, not config.json.

Looks like I made a mistake since I changed the LORA and LoCon to be combined into one, for me it has created a corrupt json file, being ui_config.json:
``
Traceback (most recent call last):
  File "C:\Program Files\Automatic1111 SD\webui\modules\ui_loadsave.py", line 30, in __init__
    self.ui_settings = self.read_from_file()
  File "C:\Program Files\Automatic1111 SD\webui\modules\ui_loadsave.py", line 132, in read_from_file
    return json.load(file)
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 932 column 5 (char 52671)
``

And just as I typed this you now posted the same error haha😄,
Another hotfix will be posted in a few mins! :)

**Comment by BlafKing** [comment]
This is now also fixed in the latest hotfix, it should also automatically repair the json you posted above when you press "Save settings as default" I've also included some prints in the CMD, which shows what settings are written. 😄

**Comment by ManOrMonster** [comment]
I saw it update it in realtime. But now there's an orphaned bracket:

<img width="270" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/daf02f12-3759-4e9f-a3db-5bad200f8804">

```
Setting adjusted: "civitai_interface/Content type:/value": ["LORA & LoCon"]
Setting adjusted: "civitai_interface/Time period:/value": "Week"
Setting adjusted: "civitai_interface/Sort by:/value": "Newest"
Setting adjusted: "civitai_interface/Save tags after download/value": true
Setting adjusted: "civitai_interface/NSFW content/value": true
Setting adjusted: "civitai_interface/Tile count:/value": 30
Setting adjusted: "civitai_interface/Tile size:/value": 8
Setting adjusted: "civitai_interface/Divide cards by date/value": false
Setting adjusted: "civitai_interface/Search type:/value": "Model name"
Setting adjusted: "civitai_interface/Filter base model:/value": ["SD 1.5", "SDXL 1.0", "Other"]
File written to: C:\stable-diffusion\automatic1111\ui-config.json
```

**Comment by BlafKing** [comment]
Welp I'll go back to bug testing 😅, Odd since it prints the right setting but doesn't properly apply it.
I'll try to find out the issue 🙃

**Comment by ManOrMonster** [comment]
I removed what I though were old entries, set my defaults in the extension filter window, clicked "Save settings as default" (showed in console), restarted, and the defaults were not loading. 

Console:
```
Setting adjusted: "civitai_interface/Divide cards by date/value": false
Setting adjusted: "civitai_interface/Search type:/value": "Model name"
Setting adjusted: "civitai_interface/Filter base model:/value": ["SD 1.5", "SDXL 1.0", "Other"]
File written to: C:\stable-diffusion\automatic1111\ui-config.json
```
As you can see, it didn't adjust nearly enough lines this time.

So I blew away all the lines and reinstalled the extension. Apparently that doesn't reinitialize the values in ui-config. How do I get the values back?

**Comment by BlafKing** [comment]
If you already removed every line then the easiest solution is to just delete the ui_config.json file entirely.
I'll now publish a new update which uses the json library to write the new settings (which I should've done in the first place lol)

Only issue is that it won't be able to repair the json file, so you'll have to either remove the file entirely, or remove the broken lines manually.

**Comment by ManOrMonster** [comment]
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/3ab59f07-e5e2-40b7-aa29-392c9e499973)

Got that one on the first try

**Comment by BlafKing** [comment]
I'll close this issue since there hasn't been an update in 3 days, if you're still experiencing the issue and would like for me to look into it further please create a new bug report with all the requested info 👍🏻
