### ISSUE TITLE
[BUG] LyCORIS removed from the filter & LORA is stuck on page 1

### ISSUE THREAD

**Issue by Terroosh** [BlafKing/sd-civitai-browser-plus#58]
**Describe the bug**
LyCORIS is no longer in the dropdown box for Content Type and after selecting LORA search results are stuck on page 1.

**To Reproduce**
1. Select LORA for content type
2. Click on Next Page

**Screenshots**
![1](https://github.com/BlafKing/sd-civitai-browser-plus/assets/55752005/e94cc320-d642-48fe-aab5-a7bf4e72ebb4)
![2](https://github.com/BlafKing/sd-civitai-browser-plus/assets/55752005/19b4c813-80fd-48f2-b1d1-7b960d8f58dc)
![3](https://github.com/BlafKing/sd-civitai-browser-plus/assets/55752005/61df140a-4a07-47fb-a22f-6085c0a30fa3)

**Additional context**
* Extension version: Version of this extension
* OS: Windows 10
* SD version: A1111 1.5.2
* Python: 3.10.6
* Branch: https://github.com/BlafKing/sd-civitai-browser-plus/commit/6682f810a6a5e503dd592f01bf52e78bd8945923

**Comment by BlafKing** [comment]
Thanks for notifying me!
LoCon's are used automatically when LORA is selected if you have toggled on the `Treat LoCon's as LORA's` setting under the in the settings menu under the CivitAI tab, which is why LoCon's don't show up as an option.

It definitely shouldn't cause the pages not to load though and I've succesfully recreated the error, so I'll start trying to fix it, thanks for notifying me about it!

**Comment by BlafKing** [comment]
This issue should now be fixed in v1.14.3, thanks again for letting me know about it! :)

I'll close this thread now since the issue should be resolved 👍🏻
