### ISSUE TITLE
[Bug]:  Wrong information when Scanning for updates

### ISSUE THREAD

**Issue by AbsolomTDaak** [BlafKing/sd-civitai-browser-plus#98]
### Describe the bug.

When you do a scan for updates, it shows as everything "has an available update", should say "is up to date".  I know, not a serious problem and is propably just changing a couple of lines of code to swap the output strings.  Just thought I would mention it in the passing

### Steps to reproduce the problem.

1. Go to Update Models
2. Press Scan for available updates after choosing what to scan
3. look at output.

### Expected behavior

Output should be swapped from "has an available update" to "is up to date"

### System info

* Extension version: Current
* OS: win 11
* SD-WebUI version: 1.16.0
* Python: 3.10.11 

### Console logs

```Shell
example:

CivitAI Browser+: terrorModelsComplete_v3Dreadless.safetensors has an available update!
CivitAI Browser+: synthwavepunk_v3Alpha.safetensors has an available update!
CivitAI Browser+: epiCPhotoGasm-softPhoto-neg.pt has an available update!
CivitAI Browser+: Starcloud.safetensors has an available update!
CivitAI Browser+: auroraICE-000012.safetensors has an available update!
CivitAI Browser+: bg.safetensors has an available update!
CivitAI Browser+: bg3.safetensors has an available update!
CivitAI Browser+: electricitylight.safetensors has an available update!
CivitAI Browser+: light.safetensors has an available update!
CivitAI Browser+: spacehole.safetensors has an available update!
CivitAI Browser+: polyhedron_skinny_all.pt has an available update!
CivitAI Browser+: rmadanegative402_sd15-neg.pt has an available update!
CivitAI Browser+: Graphic_Portrait_SD15.safetensors has an available update!
```

### Additional information

Although it still works as required, output in terminal is wrong.  Not really a bug, more of a UI fix

**Comment by BlafKing** [comment]
This is caused by having multiple versions of the same model. It scans each version and gives an available update message if the version it's currently scanning is not the latest version. It does this for every file in the selected category. So, if any file that you have installed is not the latest version, then it will get printed, regardless of if another newer version is already installed, since the print is on a per-file basis.

There isn't really an easy way to fix this so I think the best solution is to simply remove the print, it's not of much use anyway since the outdated models can be viewed in the browser.

**Comment by BlafKing** [comment]
Latest update should fix this issue, thx for bringing it to my attention! :)
It's also now possible to disable the logging of the outdated models in the console by disabling it in the settings! :)
